#!/usr/bin/env bash
# Compatibility entry point for v0.1 callers.  v0.2 is generated by
# bootstrap.py; this wrapper deliberately does not invoke APM so it remains a
# safe deterministic preview/migration command.
set -euo pipefail

SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

if [ "${1:-}" = "--detect" ]; then
  found=()
  for item in claude:.claude codex:.codex cursor:.cursor copilot:.github opencode:.opencode gemini:.gemini windsurf:.windsurf; do
    tool="${item%%:*}"; dir="${item#*:}"
    [ -e "$ROOT/$dir" ] && found+=("$tool")
  done
  case "${#found[@]}" in
    0) echo "NONE=1" ;;
    1) echo "DETECTED=${found[0]}" ;;
    *) echo "AMBIGUOUS=${found[*]}" ;;
  esac
  exit 0
fi

exec python3 "$SELF_DIR/bootstrap.py" "$@" --skip-apm
